<?php
$banners = $this->getBannerCollection();
?>
<?php if ($this->getStatus()): ?>
    <?php if (!$this->getSliderIncludeBlock()): ?>
        <div class="owl-carousel owl-theme-full" data-mage-init='{"carousel":{}}'>
            <?php foreach ($banners as $banner): ?>
                <?php if ($banner->getImage()): ?>
                    <div class="item">
                    <a target="<?php echo $banner->getTargetValue(); ?>" href="<?php echo $banner->getUrl(); ?>" title="<?php echo $banner->getImageAlt() ?>">
                    <img alt="<?php echo $banner->getImageAlt() ?>" src="<?php echo $this->getBannerImageUrl($banner->getImage()); ?>"/>
                    </a>
                    </div>
                <?php elseif ($banner->getVideo()): ?>
                    <div class="item-video"><a class="owl-video" href="<?php echo $banner->getVideo(); ?>"></a></div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    <?php else: ?>
        <div class="carousel-wrapper">
            <div class="owl-carousel owl-theme-half" data-mage-init='{"carousel":{}}'>
                <?php foreach ($banners as $banner): ?>
                    <?php if ($banner->getImage()): ?>
                        <div class="item">
                            <a target="<?php echo $banner->getTargetValue(); ?>" href="<?php echo $banner->getUrl(); ?>" title="<?php echo $banner->getImageAlt() ?>">
                            <img alt="<?php echo $banner->getImageAlt() ?>" src="<?php echo $this->getBannerImageUrl($banner->getImage()); ?>"/></a>
                        </div>
                    <?php elseif ($banner->getVideo()): ?>
                        <div class="item-video"><a class="owl-video" href="<?php echo $banner->getVideo(); ?>"></a>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
            <div class="carousel-sidebar">
                <div class="block-carousel-sidebar">
                    <?php echo $this->getSliderFirstBlock(); ?>
                </div>
                <div class="block-carousel-sidebar">
                    <?php echo $this->getSliderSecondBlock(); ?>
                </div>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>