<?php
$banners = $this->getBannerCollection();
?>

<?php if ($this->getStatus()): ?>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getViewFileUrl('Magebase_Carousel::css/animate.css') ?>">

    <?php if (!$this->getSliderIncludeBlock()): ?>
        <div class="owl-carousel owl-theme-full">
            <?php foreach ($banners as $banner): ?>
                <?php if ($banner->getImage()): ?>
                    <div class="item"><img alt="<?php echo $banner->getImageAlt() ?>"
                                           src="<?php echo $this->getBannerImageUrl($banner->getImage()); ?>"/></div>
                <?php elseif ($banner->getVideo()): ?>
                    <div class="item-video"><a class="owl-video" href="<?php echo $banner->getVideo(); ?>"></a></div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    <?php else: ?>
        <div class="carousel-wrapper">
            <div class="owl-carousel owl-theme-half">
                <?php foreach ($banners as $banner): ?>
                    <?php if ($banner->getImage()): ?>
                        <div class="item"><img alt="<?php echo $banner->getImageAlt() ?>" src="<?php echo $this->getBannerImageUrl($banner->getImage()); ?>"/></div>
                    <?php elseif ($banner->getVideo()): ?>
                        <div class="item-video"><a class="owl-video" href="<?php echo $banner->getVideo(); ?>"></a>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
            <div class="carousel-sidebar">
                <div class="block-carousel-sidebar">
                    <?php echo $this->getSliderFirstBlock(); ?>
                    <?php echo $this->getSliderFirstBlock(); ?>
                </div>
                <div class="block-carousel-sidebar">
                    <?php echo $this->getSliderSecondBlock(); ?>
                </div>
            </div>
        </div>
    <?php endif; ?>

    <script type="text/javascript">
        require(['jquery', 'magebase/carousel'], function ($) {
            $(document).ready(function ($) {
                $('.owl-carousel').owlCarousel(<?php echo $this->getOptions(); ?>);
            });
        });
    </script>
<?php endif; ?>